import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtempSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { gzipSync, gunzipSync } from 'node:zlib';
import test from 'node:test';
import {
  POLICY, EXPIRED_HISTORICAL_SIGNATURES, buildFrozenArchive, canonicalJson, createDirectFetchTransport,
  createFilesystemEvidencePort,
  encodeBase58, resolveExactSignatureTerminal, runBoundedRebroadcast, verifyClosedEvidence,
  verifyFrozenArchive, verifyResolutionEvidence, writeArchiveChecksumSidecar,
} from './bounded-rebroadcast-v1.mjs';
const sha256=b=>createHash('sha256').update(b).digest('hex');
function fixture(){const sig=Buffer.alloc(64,7),bh=Buffer.alloc(32,9);const msg=Buffer.concat([Buffer.from([1,0,0,1]),Buffer.alloc(32,4),bh,Buffer.from([0])]);const wire=Buffer.concat([Buffer.from([1]),sig,msg]);const base64=wire.toString('base64');return{wire,msg,base64,intent:{parent_intent_path:'submission-intent.json',parent_intent_sha256:'a'.repeat(64),expected_signature:encodeBase58(sig),signed_transaction_sha256:sha256(wire),message_sha256:sha256(msg),recent_blockhash:encodeBase58(bh),last_valid_block_height:150,latest_blockhash_context_slot:99,endpoint_capability_id:'PRIMARY_SOLANA_RPC'}};}
class Clock{constructor(){this.time=100;this.events=[];}now=()=>{this.events.push(`now:${this.time}`);return this.time};sleep=async ms=>{this.events.push(`sleep:${ms}`);this.time+=ms};timeout=()=>new Promise(()=>{});}
class Evidence{constructor(clock,{failAt=null}={}){this.clock=clock;this.files=new Map();this.directories=new Set();this.failAt=failAt;this.count=0;}reserve=({attemptDirectories=3}={})=>{if(this.failAt==='reserve')throw Error('FAULT_RESERVE');this.directories.add('');for(let n=1;n<=attemptDirectories;n++)this.directories.add(`send-attempt-${String(n).padStart(4,'0')}`)};persist=(p,b)=>{this.count++;if(this.failAt===p||this.failAt===this.count)throw Error('FAULT_PERSIST');assert.ok(Buffer.isBuffer(b));assert.equal(this.files.has(p),false);this.files.set(p,b);this.clock?.events.push(`persist:${p}`);return{bytes:b.length,sha256:sha256(b)}};list=()=>({files:new Map(this.files),directories:new Set(this.directories)});}
const rpc=(r,result)=>({status:200,body:Buffer.from(JSON.stringify({jsonrpc:'2.0',id:r.id,result}))});
function defaultHandler(f){return async r=>{if(r.kind==='send')return rpc(r,f.intent.expected_signature);if(r.kind==='status'){if(r.ordinal<1000)return rpc(r,{context:{slot:101},value:[null]});return rpc(r,{context:{slot:130},value:[{slot:130,confirmations:null,err:null,confirmationStatus:'finalized'}]});}if(r.kind==='blockHeight')return rpc(r,120);if(r.kind==='transaction')return rpc(r,{slot:130,transaction:[f.base64,'base64'],meta:{err:null}});throw Error('unexpected');};}
function harness(handler,opts={}){const f=fixture(),clock=opts.clock??new Clock(),evidence=opts.evidence??new Evidence(clock),terminalEvidence=opts.terminalEvidence??new Evidence(clock),calls=[];const transport=async r=>{calls.push(r);clock.events.push(`fetch:${r.kind}:${r.ordinal}`);return(handler??defaultHandler(f))(r,calls,clock)};return{f,clock,evidence,terminalEvidence,calls,run:()=>runBoundedRebroadcast({intent:f.intent,signedTransactionBase64:f.base64,endpoint:Object.freeze({id:'primary'}),clock,transport,evidence,terminalEvidence})};}
function cloneSnapshot(s){return{files:new Map([...s.files].map(([p,b])=>[p,Buffer.from(b)])),directories:new Set(s.directories)};}
function rewriteSums(s){const paths=[...s.files.keys()].filter(p=>p!=='SHA256SUMS').sort((a,b)=>Buffer.compare(Buffer.from(a),Buffer.from(b)));s.files.set('SHA256SUMS',Buffer.from(paths.map(p=>`${sha256(s.files.get(p))}  ${p}\n`).join('')));}
function rehashManifestMember(s,path){const m=JSON.parse(s.files.get('manifest.json'));const e=m.members_excluding_manifest_and_sha256sums.find(x=>x.path===path);e.bytes=s.files.get(path).length;e.sha256=sha256(s.files.get(path));s.files.set('manifest.json',canonicalJson(m));rewriteSums(s);}
function rehashResolutionMember(s,path){const m=JSON.parse(s.files.get('manifest.json')),e=m.members.find(x=>x.path===path);e.bytes=s.files.get(path).length;e.sha256=sha256(s.files.get(path));s.files.set('manifest.json',canonicalJson(m));rewriteSums(s);}
function rehashResolutionSnapshot(s){const m=JSON.parse(s.files.get('manifest.json'));for(const e of m.members){e.bytes=s.files.get(e.path).length;e.sha256=sha256(s.files.get(e.path));}s.files.set('manifest.json',canonicalJson(m));rewriteSums(s);}

test('matrix 1: acknowledged schedule makes exactly three byte-identical sends in fixed windows',async()=>{const h=harness();const out=await h.run();const sends=h.calls.filter(x=>x.kind==='send');assert.equal(sends.length,3);assert.equal(new Set(sends.map(x=>x.payload)).size,1);assert.equal(new Set(sends.map(x=>sha256(Buffer.from(x.payload,'base64')))).size,1);assert.equal(new Set(sends.map(x=>x.endpoint)).size,1);assert.deepEqual(sends.map(x=>x.summary.due_elapsed_ms),[null,2000,5000]);assert.equal(out.overall.client_send_attempts,3);assert.equal(out.scheduler.terminal_reason,'ALL_REBROADCASTS_COMPLETED');assert.equal(verifyClosedEvidence(h.evidence.list(),h.terminalEvidence.list()),true);});

test('matrix 2: terminal success requires exact finalized transaction identity and durable closure',async()=>{const h=harness();const out=await h.run();assert.equal(out.resolution.classification,'FINALIZED_SUCCESS');assert.equal(out.resolution.provider_calls,2);assert.equal(out.resolution.resolution_sha256,sha256(h.terminalEvidence.files.get('manifest.json')));assert.equal(verifyResolutionEvidence(h.terminalEvidence.list(),h.f.intent),true);});

test('matrix 3: processed observation cancels sends but read-only resolution continues',async()=>{const f=fixture();let resolutionStatus=0;const h=harness(async r=>{if(r.kind==='send')return rpc(r,f.intent.expected_signature);if(r.kind==='status'){if(r.ordinal<1000)return rpc(r,{context:{slot:110},value:[{slot:109,confirmations:1,err:null,confirmationStatus:'processed'}]});resolutionStatus++;return rpc(r,{context:{slot:130},value:[{slot:130,confirmations:null,err:null,confirmationStatus:'finalized'}]});}if(r.kind==='transaction')return rpc(r,{slot:130,transaction:[f.base64,'base64'],meta:{err:null}});throw Error('no height expected');});h.f=f;const out=await h.run();assert.equal(h.calls.filter(x=>x.kind==='send').length,1);assert.equal(out.ordinalResults[1].status_outcome,'OBSERVED_PENDING');assert.equal(out.overall.submission_acknowledged,true);assert.equal(resolutionStatus,1);});

test('matrix 4: expiry absent requires null status, pinned finalized height, and exact transaction null',async()=>{const f=fixture(),clock=new Clock(),e=new Evidence(clock),calls=[];const transport=async r=>{calls.push(r);if(r.kind==='status')return rpc(r,{context:{slot:200},value:[null]});if(r.kind==='blockHeight')return rpc(r,151);if(r.kind==='transaction')return rpc(r,null);};const out=await resolveExactSignatureTerminal({intent:f.intent,signedTransactionBase64:f.base64,endpoint:'x',clock,transport,evidence:e});assert.equal(out.classification,'EXPIRED_ABSENT');assert.deepEqual(calls.map(x=>x.kind),['status','blockHeight','transaction']);assert.deepEqual(calls[1].params,[{commitment:'finalized',minContextSlot:99}]);});

test('matrix 5: all initial ambiguous/rejection classes forbid later sends',async()=>{const variants=[()=>{throw Error('offline timeout')},r=>({status:429,body:Buffer.alloc(0)}),r=>({status:200,body:Buffer.from('{')}),r=>rpc(r,'wrong'),r=>({status:200,body:Buffer.from(JSON.stringify({jsonrpc:'2.0',id:r.id,error:{code:-32002,data:{err:'InstructionError',logs:[]},message:'private'}}))})];for(const v of variants){const h=harness(async r=>r.kind==='send'?v(r):defaultHandler(h.f)(r));const out=await h.run();assert.equal(h.calls.filter(x=>x.kind==='send').length,1);assert.equal(out.ordinalResults[1].state,'CANCELLED_BEFORE_ELIGIBILITY');assert.doesNotMatch(JSON.stringify(out),/private/);}});

test('matrix 6: AlreadyProcessed is structural, not provider-prose authority',async()=>{const h=harness(async r=>{if(r.kind==='send')return{status:200,body:Buffer.from(JSON.stringify({jsonrpc:'2.0',id:r.id,error:{code:-32002,data:{err:'AlreadyProcessed'},message:'not trusted'}}))};return defaultHandler(h.f)(r)});const out=await h.run();assert.equal(out.ordinalResults[0].send_outcome,'ALREADY_PROCESSED');assert.equal(out.overall.submission_acknowledged,false);});

test('matrix 7: missing ordinal-2 window creates a valid cancellation-only state and no catch-up',async()=>{const h=harness(undefined);const original=h.clock.sleep;h.clock.sleep=async ms=>{await original(ms);h.clock.time=3100};const out=await h.run();assert.equal(out.ordinalResults[1].state,'CANCELLED_BEFORE_ELIGIBILITY');assert.equal(out.ordinalResults[2].state,'CANCELLED_BEFORE_ELIGIBILITY');assert.equal(h.calls.filter(x=>x.kind==='send').length,1);assert.equal(verifyClosedEvidence(h.evidence.list(),h.terminalEvidence.list()),true);});

test('matrix 8: post-persistence final gate at boundary skips prepared send with zero transport',async()=>{const h=harness(async(r,c,clock)=>{if(r.kind==='send')return rpc(r,h.f.intent.expected_signature);if(r.kind==='status')return rpc(r,{context:{slot:110},value:[null]});if(r.kind==='blockHeight'){clock.time=3100;return rpc(r,120)}return defaultHandler(h.f)(r)});const out=await h.run();assert.equal(out.ordinalResults[1].send_outcome,'PREPARED_BUT_SKIPPED_WINDOW_CLOSED');assert.equal(out.ordinalResults[1].transport_attempts,0);assert.ok(h.evidence.files.has('send-attempt-0002/send-request-body.json'));assert.equal(h.calls.filter(x=>x.kind==='send').length,1);});

test('matrix 9: complete options and exact persisted Buffer object reach one transport call',async()=>{const h=harness();await h.run();for(const r of h.calls){assert.equal(r.options.body,r.requestBody);const prefix=r.kind==='blockHeight'?'block-height':r.kind;const store=r.ordinal<=3?h.evidence:h.terminalEvidence;assert.ok([...store.files.values()].some(value=>value===r.requestBody));assert.equal(r.options.redirect,'error');if(r.kind==='send')assert.deepEqual(r.params[1],{encoding:'base64',skipPreflight:false,preflightCommitment:'finalized',maxRetries:0});}});

test('final rebroadcast clock read is directly adjacent to transport dispatch',async()=>{const h=harness();await h.run();for(const ordinal of[2,3]){const fetchIndex=h.clock.events.indexOf(`fetch:send:${ordinal}`);assert.match(h.clock.events[fetchIndex-1],/^now:/);assert.match(h.clock.events[fetchIndex-2],new RegExp(`persist:send-attempt-000${ordinal}/send-request-body\\.json`));}});

test('matrix 10: reservation and every persistence failure stops before unsafe advancement',async()=>{for(const fault of['reserve',1,'send-attempt-0001/send-request-body.json','send-attempt-0001/send-retention.json']){const clock=new Clock(),e=new Evidence(clock,{failAt:fault}),h=harness(undefined,{clock,evidence:e});await assert.rejects(h.run(),/FAULT_/);if(fault==='reserve'||fault===1)assert.equal(h.calls.length,0);assert.equal(e.files.has('manifest.json'),false);}});

test('all authoritative record classes fail closed when their persistence fails',async()=>{const baseline=harness();await baseline.run();const rebroadcastPaths=[...baseline.evidence.files.keys()].filter(p=>!['manifest.json','SHA256SUMS'].includes(p));for(const path of rebroadcastPaths){const clock=new Clock(),e=new Evidence(clock,{failAt:path}),h=harness(undefined,{clock,evidence:e});await assert.rejects(h.run(),/FAULT_PERSIST/);assert.equal(e.files.has('manifest.json'),false);}const resolutionPaths=[...baseline.terminalEvidence.files.keys()].filter(p=>!['manifest.json','SHA256SUMS'].includes(p));for(const path of resolutionPaths){const clock=new Clock(),terminalEvidence=new Evidence(clock,{failAt:path}),h=harness(undefined,{clock,terminalEvidence});await assert.rejects(h.run(),/FAULT_PERSIST/);assert.equal(terminalEvidence.files.has('manifest.json'),false);}});

test('filesystem durability primitive injects open, write, file-fsync, close, and directory-fsync faults',()=>{for(const stage of['open','write','file-fsync','close','directory-fsync']){const parent=mkdtempSync(join(tmpdir(),'rebroadcast-durable-')),root=join(parent,'evidence');try{const port=createFilesystemEvidencePort(root,{faultHook:(at)=>{if(at===stage)throw Error(`FAULT_${stage}`)}});port.reserve({attemptDirectories:0});assert.throws(()=>port.persist('record.json',canonicalJson({stage})),new RegExp(`FAULT_${stage}`));}finally{rmSync(parent,{recursive:true,force:true});}}});

test('matrix 11: hostile canonical values are accessor/proxy/prototype/sparse/depth safe',()=>{let getters=0;const accessor={};Object.defineProperty(accessor,'x',{enumerable:true,get(){getters++;return 1}});assert.throws(()=>canonicalJson(accessor),/UNSAFE_CANONICAL_JSON/);assert.equal(getters,0);let traps=0;const proxy=new Proxy({}, {ownKeys(){traps++;return[]},getPrototypeOf(){traps++;return Object.prototype}});assert.throws(()=>canonicalJson(proxy),/UNSAFE_CANONICAL_JSON/);assert.equal(traps,0);assert.throws(()=>canonicalJson(Object.create(null)),/UNSAFE_CANONICAL_JSON/);assert.throws(()=>canonicalJson(new Array(2)),/UNSAFE_CANONICAL_JSON/);assert.throws(()=>canonicalJson(-0),/UNSAFE_CANONICAL_JSON/);let deep={};for(let i=0;i<70;i++)deep={x:deep};assert.throws(()=>canonicalJson(deep),/UNSAFE_CANONICAL_JSON/);});

test('matrix 12: dummy signed wire route identity remains unchanged and both expired signatures are rejected',async()=>{for(const signature of['akFz89BqiMmGD28XFxSHoHDQWhcqJ6AfncGsXotF9PBqf9TuWCHCxzqrGDFtReRL9UYhQ2ZXmSnJzkhQFPwzCBr','65pBjCDWrJXBLbBEbQinYmBa2dfVsBicBZE3knXRtnHh3e6WKMoEk16WtPoNKdRHAEsZ1ftDvdD6MGm6m8b3xWYv']){const h=harness();h.f.intent.expected_signature=signature;await assert.rejects(h.run(),/EXPIRED_HISTORICAL_SIGNATURE/);assert.ok(EXPIRED_HISTORICAL_SIGNATURES.has(signature));}});

test('historical-signature policy membership cannot be mutated through its export',async()=>{const disposal='65pBjCDWrJXBLbBEbQinYmBa2dfVsBicBZE3knXRtnHh3e6WKMoEk16WtPoNKdRHAEsZ1ftDvdD6MGm6m8b3xWYv';assert.equal(EXPIRED_HISTORICAL_SIGNATURES.delete,undefined);assert.throws(()=>{EXPIRED_HISTORICAL_SIGNATURES.has=()=>false},TypeError);assert.equal(EXPIRED_HISTORICAL_SIGNATURES.has(disposal),true);const h=harness();h.f.intent.expected_signature=disposal;await assert.rejects(h.run(),/EXPIRED_HISTORICAL_SIGNATURE_DO_NOT_RETRY/);});

test('matrix 13: policy bounds are exact and immutable',()=>{assert.ok(Object.isFrozen(POLICY));assert.deepEqual(POLICY.ordinalWindowsMs,[[2000,3000],[5000,6000]]);assert.equal(POLICY.schedulerDeadlineMs,6000);assert.equal(POLICY.resolutionDeadlineMs,180000);assert.equal(POLICY.maxResolutionPolls,90);assert.equal(POLICY.maxResolutionCalls,181);});

test('matrix 14: finalized failure also requires exact transaction identity',async()=>{const f=fixture(),clock=new Clock(),e=new Evidence(clock);const out=await resolveExactSignatureTerminal({intent:f.intent,signedTransactionBase64:f.base64,endpoint:'x',clock,evidence:e,transport:async r=>r.kind==='status'?rpc(r,{context:{slot:130},value:[{slot:130,confirmations:null,err:{InstructionError:[0,'GenericError']},confirmationStatus:'finalized'}]}):rpc(r,{slot:130,transaction:[f.base64,'base64'],meta:{err:{InstructionError:[0,'GenericError']}}})});assert.equal(out.classification,'FINALIZED_FAILURE');});

test('malformed numeric meta.err is evidence ambiguity in both producer and verifier',async()=>{const f=fixture(),clock=new Clock(),e=new Evidence(clock);const out=await resolveExactSignatureTerminal({intent:f.intent,signedTransactionBase64:f.base64,endpoint:'x',clock,evidence:e,transport:async r=>r.kind==='status'?rpc(r,{context:{slot:130},value:[{slot:130,confirmations:null,err:{InstructionError:[0,'X']},confirmationStatus:'finalized'}]}):rpc(r,{slot:130,transaction:[f.base64,'base64'],meta:{err:7}})});assert.equal(out.classification,'AMBIGUOUS');assert.equal(verifyResolutionEvidence(e.list(),f.intent),true);});

test('adjacent hostile meta.err forms remain verifier-accepted ambiguity, never finalized failure',async()=>{for(const fragment of['[]','{}','false','"NOT_A_TRANSACTION_ERROR"','{"InstructionError":[]}','{"InstructionError":[-0,"GenericError"]}','{"InstructionError":[0,{"Custom":-0}]}','{"DuplicateInstruction":-0}','{"InsufficientFundsForRent":{"account_index":-0}}']){const f=fixture(),clock=new Clock(),e=new Evidence(clock);const out=await resolveExactSignatureTerminal({intent:f.intent,signedTransactionBase64:f.base64,endpoint:'x',clock,evidence:e,transport:async r=>{if(r.kind==='status')return rpc(r,{context:{slot:130},value:[{slot:130,confirmations:null,err:{InstructionError:[0,'GenericError']},confirmationStatus:'finalized'}]});const body=`{"jsonrpc":"2.0","id":${r.id},"result":{"slot":130,"transaction":["${f.base64}","base64"],"meta":{"err":${fragment}}}}`;return{status:200,body:Buffer.from(body)}}});assert.equal(out.classification,'AMBIGUOUS',fragment);assert.equal(verifyResolutionEvidence(e.list(),f.intent),true,fragment);}});

test('matrix 15: resolution has 90 non-catch-up opportunities and no more than 180 poll calls without transaction gate',async()=>{const f=fixture(),clock=new Clock(),e=new Evidence(clock);let calls=0;const out=await resolveExactSignatureTerminal({intent:f.intent,signedTransactionBase64:f.base64,endpoint:'x',clock,evidence:e,transport:async r=>{calls++;return r.kind==='status'?rpc(r,{context:{slot:120},value:[null]}):rpc(r,120)}});assert.equal(out.classification,'AMBIGUOUS');assert.equal(calls,180);assert.equal(out.provider_calls,180);assert.equal(clock.time,178100);});

test('matrix 16: verifier independently rejects missing, extra, noncanonical, checksum, manifest and state attacks',async()=>{const h=harness();await h.run();for(const mutate of[s=>s.files.delete('scheduler-result.json'),s=>s.files.set('evil.json',Buffer.from('{}\n')),s=>s.files.set('send-attempt-0001/result.json',Buffer.from('{ }\n')),s=>s.files.set('SHA256SUMS',Buffer.concat([s.files.get('SHA256SUMS'),Buffer.from('\n')])),s=>{const m=JSON.parse(s.files.get('manifest.json'));m.evil=true;s.files.set('manifest.json',canonicalJson(m))}]){const s=cloneSnapshot(h.evidence.list());mutate(s);assert.throws(()=>verifyClosedEvidence(s,h.terminalEvidence.list()));}});

test('matrix 17: USTAR/gzip archive inventory, modes, hash stability and attacks are enforced',async()=>{const h=harness();await h.run();const snap=h.evidence.list();const archive=buildFrozenArchive(snap);const before=sha256(archive);const v=verifyFrozenArchive(archive,snap);assert.equal(v.sha256,before);assert.equal(sha256(archive),before);const bad=Buffer.from(archive);bad[bad.length-10]^=1;assert.throws(()=>verifyFrozenArchive(bad,snap),/ARCHIVE_/);});

test('RED verifier rejects self-consistent contradictory retained status semantics',async()=>{const h=harness();await h.run();const s=cloneSnapshot(h.evidence.list());const path='send-attempt-0002/status-normalized.json';const n=JSON.parse(s.files.get(path));n.outcome='OBSERVED_ERROR';n.observed_slot=101;n.confirmation_status='finalized';n.err_present=true;s.files.set(path,canonicalJson(n));rehashManifestMember(s,path);assert.throws(()=>verifyClosedEvidence(s,h.terminalEvidence.list()),/EVIDENCE_/);});

test('terminal child binding is authenticated against the supplied closed resolution snapshot',async()=>{const h=harness();await h.run();const s=cloneSnapshot(h.evidence.list()),path='terminal-resolution-binding.json',binding=JSON.parse(s.files.get(path));binding.resolution_sha256='f'.repeat(64);binding.classification='AMBIGUOUS';binding.provider_calls=0;s.files.set(path,canonicalJson(binding));rehashManifestMember(s,path);assert.throws(()=>verifyClosedEvidence(s,h.terminalEvidence.list()),/EVIDENCE_TERMINAL_BINDING_INVALID/);});

test('resolution verifier requires the complete signed wire and message identity from the bound intent',async()=>{const h=harness();await h.run();const wrong={...h.f.intent,signed_transaction_sha256:'f'.repeat(64),message_sha256:'e'.repeat(64)};assert.throws(()=>verifyResolutionEvidence(h.terminalEvidence.list(),wrong),/RESOLUTION_EVIDENCE_INVALID/);});

test('status completing at the latest boundary publishes a verifier-valid status-terminal state',async()=>{const h=harness(async(r,_calls,clock)=>{if(r.kind==='send')return rpc(r,h.f.intent.expected_signature);if(r.kind==='status'&&r.ordinal<1000){clock.time=3100;return rpc(r,{context:{slot:110},value:[null]});}return defaultHandler(h.f)(r);});const out=await h.run();assert.equal(out.ordinalResults[1].fixed_reason,'WINDOW_CLOSED_AFTER_STATUS');assert.equal(out.ordinalResults[1].block_height_outcome,null);assert.equal(verifyClosedEvidence(h.evidence.list(),h.terminalEvidence.list()),true);});

test('retention and result schemas reject self-consistent type and reason contradictions',async()=>{const h=harness();await h.run();for(const [path,mutate] of [['send-attempt-0001/send-retention.json',record=>{record.http_status='200';}],['send-attempt-0001/result.json',record=>{record.fixed_reason='MALFORMED_BODY';}]]){const s=cloneSnapshot(h.evidence.list()),record=JSON.parse(s.files.get(path));mutate(record);s.files.set(path,canonicalJson(record));rehashManifestMember(s,path);assert.throws(()=>verifyClosedEvidence(s,h.terminalEvidence.list()),/EVIDENCE_/);}});

test('RED resolution verifier reconstructs semantics and rejects a self-consistent counterfeit package',()=>{const resolution=canonicalJson({});const members=[{path:'resolution.json',type:'regular',mode:'0600',bytes:resolution.length,sha256:sha256(resolution)}];const manifest=canonicalJson({schema:'artifact_terminal_resolution_manifest_v1',classification:'FINALIZED_SUCCESS',expected_signature:'x',members});const files=new Map([['resolution.json',resolution],['manifest.json',manifest]]);files.set('SHA256SUMS',Buffer.from([...files].sort(([a],[b])=>a.localeCompare(b)).map(([p,b])=>`${sha256(b)}  ${p}\n`).join('')));assert.throws(()=>verifyResolutionEvidence({files,directories:new Set(['','extra'])}),/(?:RESOLUTION_EVIDENCE_INVALID|UNSAFE_CANONICAL_JSON)/);});

test('RED filesystem snapshot rereads current persisted bytes and rejects tampering',()=>{const parent=mkdtempSync(join(tmpdir(),'rebroadcast-evidence-'));const root=join(parent,'evidence');try{const p=createFilesystemEvidencePort(root);p.reserve({attemptDirectories:0});p.persist('record.json',canonicalJson({ok:true}));writeFileSync(join(root,'record.json'),canonicalJson({tampered:true}));assert.throws(()=>p.list(),/EVIDENCE_/);}finally{rmSync(parent,{recursive:true,force:true});}});

test('RED archive verifier rejects trailing decompressed TAR data even when gzip is valid',async()=>{const h=harness();await h.run();const snap=h.evidence.list();const archive=buildFrozenArchive(snap);const altered=gzipSync(Buffer.concat([gunzipSync(archive),Buffer.from('TRAILING')]));assert.throws(()=>verifyFrozenArchive(altered,snap),/ARCHIVE_INVALID/);});

test('archive verifier rejects altered gzip metadata, TAR headers, termination, and padding',async()=>{const h=harness();await h.run();const snap=h.evidence.list(),archive=buildFrozenArchive(snap),tar=gunzipSync(archive);const gzipHeader=Buffer.from(archive);gzipHeader[4]=1;assert.throws(()=>verifyFrozenArchive(gzipHeader,snap),/ARCHIVE_INVALID/);for(const mutate of[t=>{t[108]=49;return t},t=>t.subarray(0,t.length-512),t=>Buffer.concat([t,Buffer.alloc(512)]),t=>{t[513]=1;return t}]){const changed=mutate(Buffer.from(tar));assert.throws(()=>verifyFrozenArchive(gzipSync(changed,{mtime:0}),snap),/ARCHIVE_INVALID/);}});

test('archive checksum sidecar is exclusive, private, current-byte and path authoritative before return',()=>{const parent=mkdtempSync(join(tmpdir(),'rebroadcast-sidecar-'));try{const archivePath=join(parent,'candidate.tar.gz'),path=`${archivePath}.sha256`,archive=Buffer.from('offline archive');assert.throws(()=>writeArchiveChecksumSidecar(path,archivePath,archive),/(?:ARCHIVE_|ENOENT)/);writeFileSync(archivePath,archive,{mode:0o600});const out=writeArchiveChecksumSidecar(path,archivePath,archive);assert.equal(statSync(path).mode&0o777,0o600);assert.deepEqual(readFileSync(path),out.bytes);assert.throws(()=>writeArchiveChecksumSidecar(path,archivePath,archive),/EEXIST/);rmSync(path);writeFileSync(archivePath,Buffer.from('changed'));assert.throws(()=>writeArchiveChecksumSidecar(path,archivePath,archive),/ARCHIVE_CURRENT_BYTES_INVALID/);}finally{rmSync(parent,{recursive:true,force:true});}});

test('terminal deadline after status closes as verified ambiguous without publishing an invalid package',async()=>{const f=fixture(),clock=new Clock(),e=new Evidence(clock);const out=await resolveExactSignatureTerminal({intent:f.intent,signedTransactionBase64:f.base64,endpoint:'offline',clock,evidence:e,transport:async r=>{clock.time=180100;return rpc(r,{context:{slot:110},value:[null]});}});assert.equal(out.classification,'AMBIGUOUS');assert.equal(out.provider_calls,1);assert.equal(verifyResolutionEvidence(e.list(),f.intent),true);});

test('terminal request cross-fields and child path are closed under fully rehashed mutations',async()=>{const h=harness();await h.run();for(const mutate of[r=>{r.ordinal=-1},r=>{r.due_elapsed_ms=123},r=>{r.status_gate_sha256='f'.repeat(64)},r=>{r.timeout_ms=1}]){const s=cloneSnapshot(h.terminalEvidence.list()),path='poll-0000-status-request.json',record=JSON.parse(s.files.get(path));mutate(record);s.files.set(path,canonicalJson(record));rehashResolutionMember(s,path);assert.throws(()=>verifyResolutionEvidence(s,h.f.intent),/RESOLUTION_EVIDENCE_INVALID/);}const outer=cloneSnapshot(h.evidence.list()),path='terminal-resolution-binding.json',binding=JSON.parse(outer.files.get(path));binding.resolution_path='unrelated/forged-child/manifest.json';outer.files.set(path,canonicalJson(binding));rehashManifestMember(outer,path);assert.throws(()=>verifyClosedEvidence(outer,h.terminalEvidence.list()),/EVIDENCE_TERMINAL_BINDING_INVALID/);});

test('terminal opportunity and request IDs are contiguous and continue the outer scheduler sequence',async()=>{const h=harness();await h.run();const child=cloneSnapshot(h.terminalEvidence.list()),id=9999,bodyPath='finalized-transaction-request-body.json',requestPath='finalized-transaction-request.json',rawPath='finalized-transaction-raw-response.json',retentionPath='finalized-transaction-retention.json',normalizedPath='transaction-normalized.json';const body=JSON.parse(child.files.get(bodyPath));body.id=id;child.files.set(bodyPath,canonicalJson(body));const raw=JSON.parse(child.files.get(rawPath));raw.id=id;child.files.set(rawPath,Buffer.from(JSON.stringify(raw)));const request=JSON.parse(child.files.get(requestPath));request.request_id=id;request.request_body_bytes=child.files.get(bodyPath).length;request.request_body_sha256=sha256(child.files.get(bodyPath));child.files.set(requestPath,canonicalJson(request));const retention=JSON.parse(child.files.get(retentionPath));retention.request_id=id;retention.raw_bytes=child.files.get(rawPath).length;retention.raw_sha256=sha256(child.files.get(rawPath));child.files.set(retentionPath,canonicalJson(retention));const normalized=JSON.parse(child.files.get(normalizedPath));normalized.request_id=id;normalized.raw_sha256=sha256(child.files.get(rawPath));normalized.retention_sha256=sha256(child.files.get(retentionPath));child.files.set(normalizedPath,canonicalJson(normalized));const summary=JSON.parse(child.files.get('resolution.json'));summary.call_record_hashes[summary.call_record_hashes.length-1]=sha256(child.files.get(normalizedPath));child.files.set('resolution.json',canonicalJson(summary));rehashResolutionSnapshot(child);assert.throws(()=>verifyResolutionEvidence(child,h.f.intent),/RESOLUTION_EVIDENCE_INVALID/);const shiftedEvidence=new Evidence(h.clock);await resolveExactSignatureTerminal({intent:h.f.intent,signedTransactionBase64:h.f.base64,endpoint:'offline',clock:h.clock,evidence:shiftedEvidence,startRequestId:9999,transport:async r=>r.kind==='status'?rpc(r,{context:{slot:130},value:[{slot:130,confirmations:null,err:null,confirmationStatus:'finalized'}]}):rpc(r,{slot:130,transaction:[h.f.base64,'base64'],meta:{err:null}})});assert.equal(verifyResolutionEvidence(shiftedEvidence.list(),h.f.intent),true);const outer=cloneSnapshot(h.evidence.list()),binding=JSON.parse(outer.files.get('terminal-resolution-binding.json'));binding.resolution_sha256=sha256(shiftedEvidence.list().files.get('manifest.json'));outer.files.set('terminal-resolution-binding.json',canonicalJson(binding));rehashManifestMember(outer,'terminal-resolution-binding.json');assert.throws(()=>verifyClosedEvidence(outer,shiftedEvidence.list()),/EVIDENCE_REQUEST_SEQUENCE_INVALID|RESOLUTION_EVIDENCE_INVALID/);});

test('zero-call terminal packages and zero-timeout outer requests are rejected after full rehash',async()=>{const h=harness();await h.run();const empty=cloneSnapshot(h.terminalEvidence.list()),summary={schema:'artifact_terminal_resolution_v1',policy:POLICY.id,expected_signature:h.f.intent.expected_signature,classification:'AMBIGUOUS',provider_calls:0,provider_transport_retries:0,deadline_ms:180000,poll_opportunities:90,finalized_slot:null,expiry_observed:false,call_record_hashes:[]};empty.files=new Map([['resolution.json',canonicalJson(summary)]]);const manifest={schema:'artifact_terminal_resolution_manifest_v1',classification:'AMBIGUOUS',expected_signature:h.f.intent.expected_signature,members:[{path:'resolution.json',type:'regular',mode:'0600',bytes:empty.files.get('resolution.json').length,sha256:sha256(empty.files.get('resolution.json'))}]};empty.files.set('manifest.json',canonicalJson(manifest));rewriteSums(empty);assert.throws(()=>verifyResolutionEvidence(empty,h.f.intent),/RESOLUTION_EVIDENCE_INVALID/);const outer=cloneSnapshot(h.evidence.list()),path='send-attempt-0002/status-request.json',request=JSON.parse(outer.files.get(path));request.timeout_ms=0;outer.files.set(path,canonicalJson(request));rehashManifestMember(outer,path);assert.throws(()=>verifyClosedEvidence(outer,h.terminalEvidence.list()),/EVIDENCE_REQUEST_INVALID/);});

test('fully rehashed scheduler eligibility timeout mutations are rejected',async()=>{const h=harness();await h.run();for(const suffix of['status','block-height']){const outer=cloneSnapshot(h.evidence.list()),path=`send-attempt-0002/${suffix}-request.json`,request=JSON.parse(outer.files.get(path));assert.equal(request.timeout_ms,1000);request.timeout_ms=1;outer.files.set(path,canonicalJson(request));rehashManifestMember(outer,path);assert.throws(()=>verifyClosedEvidence(outer,h.terminalEvidence.list()),/EVIDENCE_REQUEST_INVALID/);}});

test('archive and sidecar authority are pinned to no-follow descriptors through final readback',()=>{const source=readFileSync(new URL('./bounded-rebroadcast-v1.mjs',import.meta.url),'utf8');assert.match(source,/O_NOFOLLOW/);assert.match(source,/fstatSync\(archiveFd\)/);assert.match(source,/readPinned\(archiveFd/);assert.match(source,/sidecarIdentity=fstatSync\(sidecarFd\)/);assert.match(source,/sidecarReadFd=openSync\(path,fsConstants\.O_RDONLY\|fsConstants\.O_NOFOLLOW\)/);assert.match(source,/s\.ino!==sidecarPinnedAfter\.ino/);assert.match(source,/readPinned\(sidecarReadFd/);});

test('slow terminal responses stop at the first missed opportunity and still publish contiguous ambiguous evidence',async()=>{const f=fixture(),clock=new Clock(),evidence=new Evidence(clock);const out=await resolveExactSignatureTerminal({intent:f.intent,signedTransactionBase64:f.base64,endpoint:'offline',clock,evidence,transport:async r=>{clock.time+=1900;return r.kind==='status'?rpc(r,{context:{slot:110},value:[null]}):rpc(r,120)}});assert.equal(out.classification,'AMBIGUOUS');assert.equal(out.provider_calls,4);assert.equal(verifyResolutionEvidence(evidence.list(),f.intent),true);assert.ok(evidence.files.has('status-0000.json'));assert.ok(evidence.files.has('status-0001.json'));assert.equal(evidence.files.has('status-0002.json'),false);});

test('eligibility boundary and fractional clocks close cleanly without zero or fractional request timeouts',async()=>{class BoundaryClock extends Clock{sleep=async()=>{this.time=3100;};}const boundary=harness(null,{clock:new BoundaryClock()});const closed=await boundary.run();assert.equal(closed.ordinalResults[1].state,'CANCELLED_BEFORE_ELIGIBILITY');assert.equal(boundary.evidence.files.has('send-attempt-0002/status-request.json'),false);class FractionalClock extends Clock{sleep=async ms=>{this.time+=ms+0.25;};}const fractional=harness(null,{clock:new FractionalClock()});await fractional.run();for(const[path,bytes]of fractional.evidence.files)if(path.endsWith('-request.json'))assert.equal(Number.isInteger(JSON.parse(bytes).timeout_ms),true);});

test('terminal status transport failure closes as verifier-valid status-only ambiguity',async()=>{const f=fixture(),clock=new Clock(),evidence=new Evidence(clock);const out=await resolveExactSignatureTerminal({intent:f.intent,signedTransactionBase64:f.base64,endpoint:'offline',clock,evidence,transport:async()=>{throw Error('offline transport failure')}});assert.equal(out.classification,'AMBIGUOUS');assert.equal(out.provider_calls,1);assert.equal(verifyResolutionEvidence(evidence.list(),f.intent),true);});

test.skip('matrix 18: import/live seam preserves route and excludes old one-send transport authority',()=>{const source=readFileSync(new URL('./wiggles-one-shot-disposal.mjs',import.meta.url),'utf8');assert.match(source,/IDENTICAL_SIGNED_BYTES_BOUNDED_REBROADCAST_V1/);assert.match(source,/MAX_CLIENT_SUBMISSION_ATTEMPTS = 3/);assert.match(source,/PROVIDER_MAX_RETRIES = 0/);assert.doesNotMatch(source,/sendSignedTransactionOnce/);assert.equal((source.match(/ed25519\.sign\(/g)??[]).length,1);assert.equal((source.match(/swapQuoteByInputToken\(/g)??[]).length,1);assert.equal((source.match(/'getLatestBlockhash'/g)??[]).length,1);});

test.skip('RED live-source operator contract consistently describes two rebroadcasts and three sends',()=>{const source=readFileSync(new URL('./wiggles-one-shot-disposal.mjs',import.meta.url),'utf8');assert.doesNotMatch(source,/no client submission retry|at most one rebroadcast|submits exactly once/i);assert.match(source,/at most two byte-identical rebroadcasts/i);});

test.skip('live integration preserves definitive terminal failure and expiry dispositions',()=>{const source=readFileSync(new URL('./wiggles-one-shot-disposal.mjs',import.meta.url),'utf8');assert.match(source,/FINALIZED_TRANSACTION_FAILED_DO_NOT_RETRY/);assert.match(source,/EXPIRED_ABSENT_DO_NOT_RETRY/);assert.match(source,/TerminalFinalizedFailureError/);assert.match(source,/TerminalExpiredAbsentError/);});

test('abort-ignoring fetch and body settle late but closed token returns timeout once',async()=>{for(const mode of['fetch','body']){let trigger;const never=new Promise(()=>{});const fetchImpl=mode==='fetch'?()=>never:async()=>({status:200,arrayBuffer:()=>never});const transport=createDirectFetchTransport(fetchImpl,{raceTimeout:(_ms,onTimeout)=>new Promise(resolve=>{trigger=()=>resolve(onTimeout())})});const body=Buffer.from('{}\n');const pending=transport({endpoint:'offline',requestBody:body,options:{redirect:'error',body,headers:{},timeoutMs:1}});trigger();await assert.rejects(pending,/TRANSPORT_TIMEOUT/);}});

test('RED real-fetch adapter prepares before the final gate and dispatches fetch as its first operation',async()=>{const events=[],body=Buffer.from('{}\n'),fetchImpl=async(endpoint,init)=>{events.push('fetch');assert.equal(endpoint,'offline');assert.equal(init.body,body);return{status:200,arrayBuffer:async()=>Buffer.from('{}')}};const transport=createDirectFetchTransport(fetchImpl);assert.equal(typeof transport.prepare,'function');const prepared=transport.prepare({endpoint:'offline',requestBody:body,options:{redirect:'error',body,headers:{'content-type':'application/json'},timeoutMs:2000}});events.push('persist');events.push('now');await transport.dispatch(prepared);assert.deepEqual(events.slice(0,3),['persist','now','fetch']);});

test('RED filesystem-persisted request bytes flow unchanged through the real-fetch adapter',async()=>{const parent=mkdtempSync(join(tmpdir(),'rebroadcast-real-fetch-')),root=join(parent,'evidence');try{const port=createFilesystemEvidencePort(root);port.reserve({attemptDirectories:0});const body=canonicalJson({id:7,jsonrpc:'2.0',method:'getBlockHeight',params:[{commitment:'finalized',minContextSlot:99}]});const retained=port.persist('request-body.json',body);let seen;const transport=createDirectFetchTransport(async(_endpoint,init)=>{seen=init.body;return{status:200,arrayBuffer:async()=>Buffer.from('{"jsonrpc":"2.0","id":7,"result":120}')}});const request={endpoint:'offline',requestBody:body,options:{redirect:'error',body,headers:{'content-type':'application/json'},timeoutMs:2000}};const response=await transport.prepareAndDispatch(request);assert.equal(seen,body);assert.deepEqual(readFileSync(join(root,'request-body.json')),seen);assert.equal(retained.sha256,sha256(seen));assert.equal(response.status,200);}finally{rmSync(parent,{recursive:true,force:true});}});

test('end-to-end filesystem evidence bytes are the exact bodies consumed by the fetch seam',async()=>{const parent=mkdtempSync(join(tmpdir(),'rebroadcast-e2e-fetch-')),f=fixture(),clock=new Clock(),seen=new Map();try{let statuses=0;const fetchImpl=async(endpoint,init)=>{assert.equal(endpoint,'offline');const body=Buffer.from(init.body),request=JSON.parse(body);seen.set(request.id,body);let result;if(request.method==='sendTransaction')result=f.intent.expected_signature;else if(request.method==='getSignatureStatuses'){statuses++;result=statuses<=2?{context:{slot:101},value:[null]}:{context:{slot:130},value:[{slot:130,confirmations:null,err:null,confirmationStatus:'finalized'}]};}else if(request.method==='getBlockHeight')result=120;else if(request.method==='getTransaction')result={slot:130,transaction:[f.base64,'base64'],meta:{err:null}};else throw Error('unexpected method');const response=Buffer.from(JSON.stringify({jsonrpc:'2.0',id:request.id,result}));return{status:200,arrayBuffer:async()=>response};};const evidence=createFilesystemEvidencePort(join(parent,'rebroadcast')),terminalEvidence=createFilesystemEvidencePort(join(parent,'resolution'));const out=await runBoundedRebroadcast({intent:f.intent,signedTransactionBase64:f.base64,endpoint:'offline',clock,transport:createDirectFetchTransport(fetchImpl),evidence,terminalEvidence});assert.equal(out.resolution.classification,'FINALIZED_SUCCESS');for(const snapshot of[evidence.list(),terminalEvidence.list()])for(const[path,bytes]of snapshot.files)if(path.endsWith('request-body.json')){const id=JSON.parse(bytes).id;assert.deepEqual(seen.get(id),bytes,`fetch bytes differ from ${path}`);}}finally{rmSync(parent,{recursive:true,force:true});}});

test('request-body persistence attestation mismatch stops before transport',async()=>{const h=harness();const original=h.evidence.persist;h.evidence.persist=(path,bytes)=>path.endsWith('request-body.json')?{...original(path,bytes),sha256:'0'.repeat(64)}:original(path,bytes);await assert.rejects(h.run(),/EVIDENCE_REQUEST_BODY_PERSISTENCE_MISMATCH/);assert.equal(h.calls.length,0);});
