/**
 * Trade Artifact — Devnet End-to-End Mint Test
 *
 * Flow: receipt → claim → signature → mint → PDA anchor → NFT in wallet
 *
 * This test uses a real receipt (receipt_0004_DitHyRMQ from the CsZLf8 wallet)
 * to perform a full mint on devnet.
 */

import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import {
  Keypair,
  PublicKey,
  SystemProgram,
  SYSVAR_INSTRUCTIONS_PUBKEY,
  Ed25519Program,
  Transaction,
  sendAndConfirmTransaction,
  ComputeBudgetProgram,
} from "@solana/web3.js";
import {
  TOKEN_2022_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
  getAssociatedTokenAddressSync,
} from "@solana/spl-token";
import { createHash } from "crypto";
import { expect } from "chai";

// ── Program IDL type (generated by anchor build) ────────────────────
// We'll load the IDL dynamically after build. For now, use `any`.
// After `anchor build`, replace with: import { TradeArtifact } from "../target/types/trade_artifact";

const PROGRAM_ID = new PublicKey("HBWHeRGeXUBfsNnHSgnUzqHQBxpsMUNacEJXMStz9ysQ");

// ── Test receipt data (from receipt_0004_DitHyRMQ, CsZLf8 wallet) ──
// Using a synthetic verification hash for devnet testing.
// In production, this comes from the trade artifact engine pipeline.
function createTestReceiptData() {
  // Generate a unique verification hash for this test run
  // (avoids PDA collision on re-runs)
  const uniqueSeed = `devnet-test-${Date.now()}-${Math.random()}`;
  const verificationHash = createHash("sha256")
    .update(uniqueSeed)
    .digest();

  return {
    verificationHash: Uint8Array.from(verificationHash),
    status: 0, // verified
    receiptName: "Trade Receipt #TEST",
    metadataUri: "https://arweave.net/test-placeholder-uri", // placeholder for devnet
  };
}

// ── Derive PDAs ─────────────────────────────────────────────────────

function deriveReceiptPda(verificationHash: Uint8Array): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("receipt"), Buffer.from(verificationHash)],
    PROGRAM_ID
  );
}

function deriveMintPda(verificationHash: Uint8Array): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("mint"), Buffer.from(verificationHash)],
    PROGRAM_ID
  );
}

// ── Build canonical claim message ───────────────────────────────────

function buildClaimMessage(
  verificationHash: Uint8Array,
  traderWallet: PublicKey,
  claimRecipient: PublicKey
): Buffer {
  const hashHex = Buffer.from(verificationHash).toString("hex");
  const message =
    `TRADE_RECEIPT_CLAIM_V1\n` +
    `receipt:${hashHex}\n` +
    `wallet:${traderWallet.toBase58()}\n` +
    `chain:solana\n` +
    `claim_recipient:${claimRecipient.toBase58()}`;
  return Buffer.from(message, "utf-8");
}

// ── Compute metadata hash ───────────────────────────────────────────

function computeMetadataHash(metadataUri: string): Uint8Array {
  // In production, this is SHA-256 of the actual Arweave metadata JSON.
  // For devnet testing, we hash the URI as a placeholder.
  const hash = createHash("sha256")
    .update(`{"name":"Trade Receipt #TEST","symbol":"TREC","uri":"${metadataUri}"}`)
    .digest();
  return Uint8Array.from(hash);
}

// ── Main test suite ─────────────────────────────────────────────────

describe("trade_artifact devnet mint", () => {
  // Load provider from Anchor.toml (devnet + devnet-vault.json)
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const payer = (provider.wallet as anchor.Wallet).payer;
  const connection = provider.connection;

  // For devnet test: trader = payer = recipient (same wallet, simplest case)
  const traderWallet = payer;
  const claimRecipient = payer.publicKey;

  let program: Program;
  let testData: ReturnType<typeof createTestReceiptData>;
  let receiptPda: PublicKey;
  let receiptBump: number;
  let mintPda: PublicKey;
  let mintBump: number;
  let recipientAta: PublicKey;
  let claimMessage: Buffer;
  let claimSignature: Uint8Array;
  let metadataHash: Uint8Array;

  before(async () => {
    // Load program (IDL is generated by anchor build)
    const idl = await Program.fetchIdl(PROGRAM_ID, provider);
    if (!idl) {
      throw new Error(
        "IDL not found on-chain. Deploy with `anchor deploy` first."
      );
    }
    program = new Program(idl, provider);

    // Generate unique test data
    testData = createTestReceiptData();

    // Derive PDAs
    [receiptPda, receiptBump] = deriveReceiptPda(testData.verificationHash);
    [mintPda, mintBump] = deriveMintPda(testData.verificationHash);

    // Recipient ATA (Token-2022)
    recipientAta = getAssociatedTokenAddressSync(
      mintPda,
      claimRecipient,
      false, // not PDA owner
      TOKEN_2022_PROGRAM_ID
    );

    // Build and sign claim message
    claimMessage = buildClaimMessage(
      testData.verificationHash,
      traderWallet.publicKey,
      claimRecipient
    );

    // Ed25519 sign the claim message with trader wallet
    claimSignature = nacl_sign(claimMessage, traderWallet.secretKey);

    // Compute metadata hash
    metadataHash = computeMetadataHash(testData.metadataUri);

    console.log("=== Test Setup ===");
    console.log("Payer:", payer.publicKey.toBase58());
    console.log("Trader:", traderWallet.publicKey.toBase58());
    console.log("Recipient:", claimRecipient.toBase58());
    console.log("Verification hash:", Buffer.from(testData.verificationHash).toString("hex").slice(0, 16) + "...");
    console.log("Receipt PDA:", receiptPda.toBase58());
    console.log("Mint PDA:", mintPda.toBase58());
    console.log("Recipient ATA:", recipientAta.toBase58());
    console.log("Claim message length:", claimMessage.length, "bytes");
    console.log("");
  });

  it("mints a trade receipt NFT on devnet", async () => {
    // ── Build transaction ───────────────────────────────────────
    // Instruction 0: Ed25519 signature verification
    const ed25519Ix = Ed25519Program.createInstructionWithPrivateKey({
      privateKey: traderWallet.secretKey.slice(0, 32),
      message: claimMessage,
    });

    // Instruction 1: Compute budget (Token-2022 + Ed25519 needs headroom)
    const computeIx = ComputeBudgetProgram.setComputeUnitLimit({
      units: 400_000,
    });

    // Instruction 2: mint_receipt
    const mintIx = await program.methods
      .mintReceipt(
        Array.from(testData.verificationHash),      // verification_hash: [u8; 32]
        Array.from(metadataHash),                     // metadata_hash: [u8; 32]
        Array.from(claimSignature),                   // claim_signature: [u8; 64]
        claimMessage,                                 // claim_message: Vec<u8>
        testData.status,                              // status: u8
        testData.metadataUri,                         // metadata_uri: String
        testData.receiptName,                         // receipt_name: String
      )
      .accounts({
        payer: payer.publicKey,
        traderWallet: traderWallet.publicKey,
        claimRecipient: claimRecipient,
        receiptAnchor: receiptPda,
        nftMint: mintPda,
        recipientTokenAccount: recipientAta,
        tokenProgram: TOKEN_2022_PROGRAM_ID,
        associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
        instructionsSysvar: SYSVAR_INSTRUCTIONS_PUBKEY,
      })
      .instruction();

    // ── Send transaction ────────────────────────────────────────
    const tx = new Transaction()
      .add(ed25519Ix)
      .add(computeIx)
      .add(mintIx);

    console.log("Sending mint transaction...");
    const txSig = await sendAndConfirmTransaction(
      connection,
      tx,
      [payer],
      { commitment: "confirmed" }
    );
    console.log("✅ Transaction confirmed:", txSig);
    console.log(`   Explorer: https://explorer.solana.com/tx/${txSig}?cluster=devnet`);

    // ── Verify PDA ──────────────────────────────────────────────
    console.log("\nVerifying receipt PDA...");
    const receiptAccount = await program.account.receiptAnchor.fetch(receiptPda);

    expect(Buffer.from(receiptAccount.verificationHash)).to.deep.equal(
      Buffer.from(testData.verificationHash)
    );
    expect(Buffer.from(receiptAccount.metadataHash)).to.deep.equal(
      Buffer.from(metadataHash)
    );
    expect(receiptAccount.traderWallet.toBase58()).to.equal(
      traderWallet.publicKey.toBase58()
    );
    expect(receiptAccount.claimRecipient.toBase58()).to.equal(
      claimRecipient.toBase58()
    );
    expect(receiptAccount.status).to.equal(testData.status);
    expect(receiptAccount.programVersion).to.equal(1);
    expect(receiptAccount.mint.toBase58()).to.equal(mintPda.toBase58());
    expect(receiptAccount.bump).to.equal(receiptBump);
    expect(receiptAccount.mintedAt.toNumber()).to.be.greaterThan(0);

    console.log("✅ PDA data verified:");
    console.log("   Status:", receiptAccount.status);
    console.log("   Program version:", receiptAccount.programVersion);
    console.log("   Mint:", receiptAccount.mint.toBase58());
    console.log("   Minted at:", new Date(receiptAccount.mintedAt.toNumber() * 1000).toISOString());

    // ── Verify NFT in wallet ────────────────────────────────────
    console.log("\nVerifying NFT in recipient wallet...");
    const ataInfo = await connection.getTokenAccountBalance(recipientAta);
    expect(ataInfo.value.uiAmount).to.equal(1);
    expect(ataInfo.value.decimals).to.equal(0);
    console.log("✅ NFT found in wallet: amount =", ataInfo.value.uiAmount);

    // ── Verify mint has no authority (supply locked at 1) ───────
    const mintInfo = await connection.getAccountInfo(mintPda);
    console.log("✅ Mint account exists, size:", mintInfo?.data.length, "bytes");

    // ── Summary ─────────────────────────────────────────────────
    console.log("\n=== MINT SUCCESSFUL ===");
    console.log("TX Signature:", txSig);
    console.log("PDA Address:", receiptPda.toBase58());
    console.log("NFT Mint:", mintPda.toBase58());
    console.log("Recipient ATA:", recipientAta.toBase58());
    console.log("Explorer:", `https://explorer.solana.com/tx/${txSig}?cluster=devnet`);
  });

  it("verify_receipt succeeds for the minted receipt", async () => {
    const tx = await program.methods
      .verifyReceipt(Array.from(testData.verificationHash))
      .accounts({
        receiptAnchor: receiptPda,
      })
      .rpc({ commitment: "confirmed" });

    console.log("✅ verify_receipt succeeded:", tx);
  });

  it("rejects duplicate mint (PDA already exists)", async () => {
    // Attempting to mint the same verification_hash again should fail
    // because the receipt PDA already exists.
    const ed25519Ix = Ed25519Program.createInstructionWithPrivateKey({
      privateKey: traderWallet.secretKey.slice(0, 32),
      message: claimMessage,
    });

    const computeIx = ComputeBudgetProgram.setComputeUnitLimit({
      units: 400_000,
    });

    try {
      const mintIx = await program.methods
        .mintReceipt(
          Array.from(testData.verificationHash),
          Array.from(metadataHash),
          Array.from(claimSignature),
          claimMessage,
          testData.status,
          testData.metadataUri,
          testData.receiptName,
        )
        .accounts({
          payer: payer.publicKey,
          traderWallet: traderWallet.publicKey,
          claimRecipient: claimRecipient,
          receiptAnchor: receiptPda,
          nftMint: mintPda,
          recipientTokenAccount: recipientAta,
          tokenProgram: TOKEN_2022_PROGRAM_ID,
          associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
          systemProgram: SystemProgram.programId,
          instructionsSysvar: SYSVAR_INSTRUCTIONS_PUBKEY,
        })
        .instruction();

      const tx = new Transaction()
        .add(ed25519Ix)
        .add(computeIx)
        .add(mintIx);

      await sendAndConfirmTransaction(connection, tx, [payer], {
        commitment: "confirmed",
      });

      // If we get here, the test failed — should have thrown
      expect.fail("Duplicate mint should have been rejected");
    } catch (err: any) {
      console.log("✅ Duplicate mint correctly rejected:", err.message?.slice(0, 80));
    }
  });
});

// ── Ed25519 signing helper ──────────────────────────────────────────
// Using tweetnacl-compatible signing from the 64-byte secret key

function nacl_sign(message: Buffer, secretKey: Uint8Array): Uint8Array {
  // @solana/web3.js Ed25519Program.createInstructionWithPrivateKey
  // handles the actual crypto. We need the raw signature for our
  // instruction args. Use tweetnacl for raw Ed25519 sign.
  const nacl = require("tweetnacl");
  const sig = nacl.sign.detached(message, secretKey);
  return sig;
}
