#!/usr/bin/env node
import assert from 'node:assert/strict';
import { buildWalletAcquisitionResultV1 } from './acquisition-result.mjs';
import { buildActivityFindingV1 } from './activity-findings.mjs';
import { recomputeCoverageV1 } from './coverage.mjs';
import { buildCandidateEvidenceBundleV1 } from './evidence-bundle.mjs';
import { buildDispositionV1, buildEventRecordV1, computeCandidateDigest, computeCandidateSetDigest, computeSourceTransactionDigest } from './identity.mjs';
import { buildMarkObservationV1 } from './mark-observations.mjs';
import { GENESIS_HASH, validateCandidateSetV1 } from './schema.mjs';
import { buildWalletCandidateSetV1, validateWalletCandidateSetV1AgainstEvidenceBundle } from './builder.mjs';
import { providerPublicKey, providerSignature } from '../wallet-acquisition/fixtures/test-identities.mjs';

const WALLET = providerPublicKey('wallet');
const QUOTE = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';
const CLOSED = providerPublicKey('CLOSED');
const OPEN = providerPublicKey('OPEN');
const BLOCKED = providerPublicKey('BLOCKED');
const BLOCKED_2 = providerPublicKey('BLOCKED-2');
const scope = { scope_version: 'wallet_candidate_scope_input_v1', chain: 'solana', network: 'mainnet-beta', genesis_hash: GENESIS_HASH, wallet: WALLET, window: { window_version: 'fixed_lookback_latest_state_v1', lookback_profile: 'lookback_30d_v1', requested_lookback_seconds: 2592000, initial_before_signature: null, lower_bound: { oldest_allowed_timestamp: 1, completion_status: 'proven' } } };
const profiles = { wallet_acquisition_profile: 'wallet_wide_bounded_history_v1', wallet_normalization_profile: 'artifact_wallet_wide_solana_spot_normalization_v1', reconstruction_engine_version: 'artifact_position_ledger_receipt_v1', accounting_method_version: 'weighted_average_position_accounting_v1', mark_profile: 'direct_quote_mark_v1', mark_max_age_seconds: 300 };
const boundary = { boundary_version: 'solana_finalized_acquisition_boundary_v1', chain: 'solana', network: 'mainnet-beta', genesis_hash: GENESIS_HASH, commitment: 'finalized', anchor_slot: 100, anchor_block_time: 2592001, anchor_blockhash: providerPublicKey('blockhash'), history_complete_through_anchor: true, lower_bound_completion_proven: true, boundary_status: 'proven' };
const inputStatus = { coverage_status: 'complete', acquisition_complete: true, normalization_complete: true, classification_complete: true, pagination_complete: true, historical_bound_proven: true, chain_boundary_proven: true, truncated: false, capped: false, partial: false, provider_uncertain: false };
function raw({ token, time, tx, index, buy, base = 5, quote = 10 }) { return { wallet: WALLET, timestamp: time, tx_hash: providerSignature(tx), source: 'swap', token_in_mint: buy ? QUOTE : token, token_in_amount: buy ? quote : base, token_in_decimals: 6, token_out_mint: buy ? token : QUOTE, token_out_amount: buy ? base : quote, token_out_decimals: 6, extraction_method: 'balance_delta', raw_index: index }; }
const rawEvents = [raw({ token: CLOSED, time: 100, tx: 'tx-a-buy', index: 0, buy: true }), raw({ token: OPEN, time: 200, tx: 'tx-b-buy', index: 1, buy: true, base: 4, quote: 8 }), raw({ token: CLOSED, time: 300, tx: 'tx-a-sell', index: 2, buy: false, quote: 15 })];
const events = rawEvents.map((slice7_event, index) => buildEventRecordV1({ source_slot: 10 + index, slice7_event }));
const supported = events.map(event => buildDispositionV1({ tx_hash: event.slice7_event.tx_hash, slot: event.source_slot, block_time: event.slice7_event.timestamp, disposition_type: 'supported_normalized_event', affected_token_mints: [event.slice7_event.token_in_mint === QUOTE ? event.slice7_event.token_out_mint : event.slice7_event.token_in_mint], normalized_event_digests: [event.event_digest], finding_digests: [] }));
const blockedSource = { tx_hash: providerSignature('tx-blocked'), slot: 20, block_time: 400 };
const finding = buildActivityFindingV1({ finding_type: 'unsupported_activity', severity: 'candidate_blocking', impact_scope: 'token_specific', time_range: { first_observed_at: 400, last_observed_at: 400, first_observed_slot: 20, last_observed_slot: 20 }, affected_token_mints: [BLOCKED], affected_quote_mints: [QUOTE], source_transaction_digests: [computeSourceTransactionDigest(blockedSource)], source_event_digests: [], reason_codes: ['unsupported_swap_shape'], impact: { blocks_candidate_projection: true, blocks_receipt_publication: true }, disclosure_codes: ['activity_not_reconstructable'] });
const blockedDisposition = buildDispositionV1({ ...blockedSource, disposition_type: 'unsupported_activity', affected_token_mints: [BLOCKED], normalized_event_digests: [], finding_digests: [finding.finding_digest] });
const blockedSource2 = { tx_hash: providerSignature('tx-blocked-2'), slot: 21, block_time: 410 };
const finding2 = buildActivityFindingV1({ finding_type: 'unsupported_activity', severity: 'candidate_blocking', impact_scope: 'token_specific', time_range: { first_observed_at: 410, last_observed_at: 410, first_observed_slot: 21, last_observed_slot: 21 }, affected_token_mints: [BLOCKED_2], affected_quote_mints: [QUOTE], source_transaction_digests: [computeSourceTransactionDigest(blockedSource2)], source_event_digests: [], reason_codes: ['unsupported_transfer_activity'], impact: { blocks_candidate_projection: true, blocks_receipt_publication: true }, disclosure_codes: ['activity_not_reconstructable'] });
const blockedDisposition2 = buildDispositionV1({ ...blockedSource2, disposition_type: 'unsupported_activity', affected_token_mints: [BLOCKED_2], normalized_event_digests: [], finding_digests: [finding2.finding_digest] });
const dispositions = [...supported, blockedDisposition, blockedDisposition2].sort((a, b) => a.slot - b.slot);
const findings = [finding, finding2];
const coverage = recomputeCoverageV1({ transactionDispositions: dispositions, normalizedEventRecords: events, activityFindings: findings, boundary, inputStatus, paginationTerminalReason: 'historical_bound_reached' });
const acquisitionResult = buildWalletAcquisitionResultV1({ acquisition_result_version: 'wallet_wide_acquisition_result_v1', scope, profiles: { ...profiles, mark_profile: null, mark_max_age_seconds: null }, boundary, input_status: inputStatus, coverage, transaction_dispositions: dispositions, normalized_event_records: events, activity_findings: findings });
const mark = buildMarkObservationV1({ token_mint: OPEN, quote_mint: QUOTE, observation_status: 'available', source_profile: 'direct_quote_mark_v1', mark_price_raw_quote: 3, observed_at: 2591991, source_slot: 99, reason_code: null });
const evidenceBundle = buildCandidateEvidenceBundleV1({ acquisitionResult, markObservations: [mark], profiles });
const set = buildWalletCandidateSetV1({ evidenceBundle });
assert.equal(set.candidate_set_version, 'wallet_candidate_set_v1');
assert.doesNotThrow(() => validateCandidateSetV1(set));
assert.doesNotThrow(() => validateWalletCandidateSetV1AgainstEvidenceBundle(set, evidenceBundle));
assert.equal(set.payload.counts.candidate_count, 2);
assert.equal(set.payload.counts.closed_candidate_count, 1);
assert.equal(set.payload.counts.open_candidate_count, 1);
assert.equal(set.payload.counts.selectable_candidate_count, 1);
assert.equal(set.payload.counts.blocked_summary_count, 2);
assert.equal(set.payload.counts.finding_count, 2);
assert.deepEqual(set.payload.candidates.map(item => item.candidate_digest), [...set.payload.candidates.map(item => item.candidate_digest)].sort());
assert.deepEqual(new Set(set.payload.blocked_summaries.map(item => item.token_mint)), new Set([BLOCKED,BLOCKED_2]));
assert.ok(!set.payload.candidates.some(item => item.projection.token_mint === BLOCKED));
const open = set.payload.candidates.find(item => item.projection.token_mint === OPEN);
assert.equal(open.projection.snapshot.snapshot_at, boundary.anchor_block_time);
assert.equal(open.projection.snapshot.unrealized_pnl.market_value_quote, 12);
assert.equal(set.payload.commitments.evidence_bundle_digest, evidenceBundle.evidence_bundle_digest);
assert.ok(!JSON.stringify(set.payload).includes('candidate_set_digest'));
assert.ok(Object.isFrozen(set) && Object.isFrozen(set.payload) && Object.isFrozen(set.payload.candidates));

const wrongCounts = structuredClone(set); wrongCounts.payload.counts.candidate_count = 99;
assert.throws(() => validateWalletCandidateSetV1AgainstEvidenceBundle(wrongCounts, evidenceBundle), error => error.code === 'candidate_set_count_mismatch' || error.code === 'digest_mismatch');
const blockedCandidateSet = structuredClone(set); blockedCandidateSet.payload.candidates[0].projection.token_mint = BLOCKED;
assert.throws(() => validateWalletCandidateSetV1AgainstEvidenceBundle(blockedCandidateSet, evidenceBundle));
const forgedEconomics = structuredClone(set);
const forgedCandidate = forgedEconomics.payload.candidates.find(item => item.projection.token_mint === CLOSED);
forgedCandidate.projection.economics.realized_pnl_quote = 999;
forgedCandidate.candidate_digest = computeCandidateDigest(forgedCandidate);
forgedCandidate.candidate_id = `acv1_${forgedCandidate.candidate_digest}`;
forgedCandidate.handoff.candidate_digest = forgedCandidate.candidate_digest;
forgedEconomics.payload.candidates.sort((a, b) => a.candidate_digest.localeCompare(b.candidate_digest));
forgedEconomics.candidate_set_digest = computeCandidateSetDigest(forgedEconomics);
assert.doesNotThrow(() => validateCandidateSetV1(forgedEconomics));
assert.throws(() => validateWalletCandidateSetV1AgainstEvidenceBundle(forgedEconomics, evidenceBundle), error => error.code === 'candidate_projection_mismatch');
console.log('candidate-set builder: PASS');
